[package]
name = "elipcian"
version = "0.1.0"
authors = ["h416 <h416@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = { version = "0.21", default-features = false, features = ["jpeg", "png_codec"] }
rand = "0.7"
raqote = "0.5"
euclid = "0.19"
sw-composite = "0.5"
font-kit = "0.3"
