[package]
name = "elliptician"
version = "0.1.0"
authors = ["h416 <h416@users.noreply.github.com>"]
edition = "2018"

[dependencies]
euclid = "0.20"
image = { version = "0.22", default-features = false, features = ["jpeg", "png_codec"] }
rand = "0.7"
raqote = { version = "0.6", default-features = false }
pico-args = "0.2"
lab = "0.7"
read_color = "1.0"
